name: Spell Check

on:
  pull_request:
    paths:
      - 'content/**/*.md'
      - 'archetypes/**/*.md'
      - '*.md'
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install cspell
        run: npm install -g cspell
        
      - name: Run spell check
        run: |
          cspell "content/**/*.md" "archetypes/**/*.md" "*.md" \
            --config .cspell.json \
            --no-progress \
            --show-context
